# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  productsservice-app:
    image: productsservice
    hostname: productsservice-app
    container_name: productsservice-app
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_JDBC_URL=jdbc:postgresql://productsservice-postgresql:5432/productsservice
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://productsservice-postgresql:5432/productsservice
      - FLETA_SLEEP=30 # gives time for other services to boot before the application
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 127.0.0.1:8086:8086
#  productsservice-postgresql:
#    image: postgres:13.2
#    hostname: productsservice-postgresql
#    container_name: productsservice-postgresql
#    # volumes:
#    #   - ~/volumes/fleta/productsservice/postgresql/:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=productsservice
#      - POSTGRES_PASSWORD=
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    # If you want to expose these ports outside your dev PC,
#    # remove the "127.0.0.1:" prefix
#    ports:
#      - 127.0.0.1:5432:5432
  kafka:
    image: confluentinc/cp-kafka:5.5.3
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    hostname: kafka
    container_name: kafka
    ports:
      - 127.0.0.1:9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-ui:
    image: provectuslabs/kafka-ui
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - 127.0.0.1:9999:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
